package ide.sketch.compiler;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Mar 19 17:46:58 EDT 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 16;
  public static final int STRING_LITERAL = 26;
  public static final int CHAR_LITERAL = 27;
  public static final int CASE = 20;
  public static final int SEMI = 2;
  public static final int INT = 35;
  public static final int ASSING = 18;
  public static final int FOR = 17;
  public static final int DEFINE = 29;
  public static final int TYPE = 4;
  public static final int LP = 5;
  public static final int COMMA = 3;
  public static final int RP = 6;
  public static final int UNARYOP = 34;
  public static final int IF = 13;
  public static final int DOT = 19;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int LC = 9;
  public static final int LB = 7;
  public static final int RETURN = 12;
  public static final int BINARYOP = 33;
  public static final int error = 1;
  public static final int RC = 10;
  public static final int RB = 8;
  public static final int INCLUDE = 30;
  public static final int NULL = 28;
  public static final int BREAK = 15;
  public static final int SWITCH = 23;
  public static final int COLON = 31;
  public static final int ELSE = 14;
  public static final int WHILE = 24;
  public static final int CONSTANTE_LOGICA = 25;
  public static final int DEFAULT = 21;
  public static final int STRUCT = 11;
  public static final int DO = 22;
}

